env:
  matrix:
    secure: Ibi2QsrlZIm9p5WQktDh8rv55Y81pWMcOA1RXRA1UW9Vgvwhe5Dm4z3JID86IfJFPCg8AG0C3iCwYIONsXs3bmTum1z0PMyOnrpS6PGJNyOoxv7c76aqKwScA0gD+85eKFoqP1emMds79aoLLuVhENkrGUrUWOWIbYUdFeOdfINSE4Hp21asZqxrT3ovp3G52fe9hHjO6B9sgNe+kSOPc8slJcd4XgWgwS+w7iY3qkcrvs/vkQPgLQzxfj9JaPrNpF35yN45WGxNyPFl1TPaR3r8yQm0KCNFjtbznVQBJWnjTNgmRx/xmiKDCxCttUKqf/4CJL11C0JQW5PfugVr0EE/XyZ969kCSVRykXSLo74NvLJpZT01WiLmhEZ0hJeWEg18+B26CHXISPPbR6UzqMHhnhvaU3ltyp0fIusbOtULB2W5jYhCxzXuFTQLpHsgbBi4yCW3C9A0U0c44Ks0A6QHVvPBkal3zKOiAHB9LJTdpOfPALE5hkgAn+7xjXf3OTXHFj3pc4jQJjrOlBkHWiQlGZ8acYtFFkCjpmgJMscycTHVsyXyG6Dp15QHBmCsm90u2NXCM35A7p4b29H6ymyOIn9XWJoMahMyIMJftDc4RMBU489uU6Awv2LbiMj7MYAdLj4NctwHpaRDKPBAs3Gf+7uBK+zUBTsSdrPIG7Y=

sudo: required
services:
  - docker

dist: xenial

language: bash

script:
  - ./build.sh
